%resource male-first-name: 
	"Aaron" | "Abdul" | "Abe" | "Abel" | "Abraham" | "Abram" | "Adalberto" | "Adam" | "Adan" | "Adolfo" | "Adolph" | "Adrian" | "Agustin" 
	| "Ahmad" | "Ahmed" | "Al" | "Alan" | "Albert" | "Alberto" | "Alden" | "Aldo" | "Alec" | "Alejandro" | "Alex" | "Alexander" 
	| "Alexis" | "Alfonso" | "Alfonzo" | "Alfred" | "Alfredo" | "Ali" | "Allan" | "Allen" | "Alonso" | "Alonzo" | "Alphonse" | "Alphonso" 
	| "Alton" | "Alva" | "Alvaro" | "Alvin" | "Amado" | "Ambrose" | "Amos" | "Anderson" | "Andre" | "Andrea" | "Andreas" | "Andres" 
	| "Andrew" | "Andy" | "Angel" | "Angelo" | "Anibal" | "Anthony" | "Antione" | "Antoine" | "Anton" | "Antone" | "Antonia" | "Antonio" 
	| "Antony" | "Antwan" | "Archie" | "Arden" | "Ariel" | "Arlen" | "Arlie" | "Armand" | "Armando" | "Arnold" | "Arnoldo" | "Arnulfo" 
	| "Aron" | "Arron" | "Art" | "Arthur" | "Arturo" | "Asa" | "Ashley" | "Aubrey" | "August" | "Augustine" | "Augustus" | "Aurelio" 
	| "Austin" | "Avery" | "Barney" | "Barrett" | "Barry" | "Bart" | "Barton" | "Basil" | "Beau" | "Ben" | "Benedict" | "Benito" 
	| "Benjamin" | "Bennett" | "Bennie" | "Benny" | "Benton" | "Bernard" | "Bernardo" | "Bernie" | "Berry" | "Bert" | "Bertram" | "Bill" 
	| "Billie" | "Billy" | "Blaine" | "Blair" | "Blake" | "Bo" | "Bob" | "Bobbie" | "Bobby" | "Booker" | "Boris" | "Boyce" | "Boyd" 
	| "Brad" | "Bradford" | "Bradley" | "Bradly" | "Brady" | "Brain" | "Branden" | "Brandon" | "Brant" | "Brendan" | "Brendon" | "Brent" 
	| "Brenton" | "Bret" | "Brett" | "Brian" | "Brice" | "Britt" | "Brock" | "Broderick" | "Brooks" | "Bruce" | "Bruno" | "Bryan" 
	| "Bryant" | "Bryce" | "Bryon" | "Buck" | "Bud" | "Buddy" | "Buford" | "Burl" | "Burt" | "Burton" | "Buster" | "Byron" | "Caleb" 
	| "Calvin" | "Cameron" | "Carey" | "Carl" | "Carlo" | "Carlos" | "Carlton" | "Carmelo" | "Carmen" | "Carmine" | "Carol" | "Carrol" 
	| "Carroll" | "Carson" | "Carter" | "Cary" | "Casey" | "Cecil" | "Cedric" | "Cedrick" | "Cesar" | "Chad" | "Chadwick" | "Chance" 
	| "Chang" | "Charles" | "Charley" | "Charlie" | "Chas" | "Chase" | "Chauncey" | "Chester" | "Chet" | "Chi" | "Chong" | "Chris" 
	| "Christian" | "Christoper" | "Christopher" | "Chuck" | "Chung" | "Clair" | "Clarence" | "Clark" | "Claud" | "Claude" | "Claudio" 
	| "Clay" | "Clayton" | "Clement" | "Clemente" | "Cleo" | "Cletus" | "Cleveland" | "Cliff" | "Clifford" | "Clifton" | "Clint" 
	| "Clinton" | "Clyde" | "Cody" | "Colby" | "Cole" | "Coleman" | "Colin" | "Collin" | "Colton" | "Columbus" | "Connie" | "Conrad" 
	| "Cordell" | "Corey" | "Cornelius" | "Cornell" | "Cortez" | "Cory" | "Courtney" | "Coy" | "Craig" | "Cristobal" | "Cristopher" 
	| "Cruz" | "Curt" | "Curtis" | "Cyril" | "Cyrus" | "Dale" | "Dallas" | "Dalton" | "Damian" | "Damien" | "Damion" | "Damon" | "Dan" 
	| "Dana" | "Dane" | "Danial" | "Daniel" | "Danilo" | "Dannie" | "Danny" | "Dante" | "Darell" | "Daren" | "Darin" | "Dario" | "Darius" 
	| "Darnell" | "Daron" | "Darrel" | "Darrell" | "Darren" | "Darrick" | "Darrin" | "Darron" | "Darryl" | "Darwin" | "Daryl" | "Dave" 
	| "David" | "Davis" | "Dean" | "Deandre" | "Deangelo" | "Dee" | "Del" | "Delbert" | "Delmar" | "Delmer" | "Demarcus" | "Demetrius" 
	| "Denis" | "Dennis" | "Denny" | "Denver" | "Deon" | "Derek" | "Derick" | "Derrick" | "Deshawn" | "Desmond" | "Devin" | "Devon" 
	| "Dewayne" | "Dewey" | "Dewitt" | "Dexter" | "Dick" | "Diego" | "Dillon" | "Dino" | "Dion" | "Dirk" | "Domenic" | "Domingo" 
	| "Dominic" | "Dominick" | "Dominique" | "Don" | "Donald" | "Dong" | "Donn" | "Donnell" | "Donnie" | "Donny" | "Donovan" | "Donte" 
	| "Dorian" | "Dorsey" | "Doug" | "Douglas" | "Douglass" | "Doyle" | "Drew" | "Duane" | "Dudley" | "Duncan" | "Dustin" | "Dusty" 
	| "Dwain" | "Dwayne" | "Dwight" | "Dylan" | "Earl" | "Earle" | "Earnest" | "Ed" | "Eddie" | "Eddy" | "Edgar" | "Edgardo" | "Edison" 
	| "Edmond" | "Edmund" | "Edmundo" | "Eduardo" | "Edward" | "Edwardo" | "Edwin" | "Efrain" | "Efren" | "Elbert" | "Elden" | "Eldon" 
	| "Eldridge" | "Eli" | "Elias" | "Elijah" | "Eliseo" | "Elisha" | "Elliot" | "Elliott" | "Ellis" | "Ellsworth" | "Elmer" | "Elmo" 
	| "Eloy" | "Elroy" | "Elton" | "Elvin" | "Elvis" | "Elwood" | "Emanuel" | "Emerson" | "Emery" | "Emil" | "Emile" | "Emilio" 
	| "Emmanuel" | "Emmett" | "Emmitt" | "Emory" | "Enoch" | "Enrique" | "Erasmo" | "Eric" | "Erich" | "Erick" | "Erik" | "Erin" 
	| "Ernest" | "Ernesto" | "Ernie" | "Errol" | "Ervin" | "Erwin" | "Esteban" | "Ethan" | "Eugene" | "Eugenio" | "Eusebio" | "Evan" 
	| "Everett" | "Everette" | "Ezekiel" | "Ezequiel" | "Ezra" | "Fabian" | "Faustino" | "Fausto" | "Federico" | "Felipe" | "Felix" 
	| "Felton" | "Ferdinand" | "Fermin" | "Fernando" | "Fidel" | "Filiberto" | "Fletcher" | "Florencio" | "Florentino" | "Floyd" 
	| "Forest" | "Forrest" | "Foster" | "Frances" | "Francesco" | "Francis" | "Francisco" | "Frank" | "Frankie" | "Franklin" | "Franklyn" 
	| "Fred" | "Freddie" | "Freddy" | "Frederic" | "Frederick" | "Fredric" | "Fredrick" | "Freeman" | "Fritz" | "Gabriel" | "Gail" 
	| "Gale" | "Galen" | "Garfield" | "Garland" | "Garret" | "Garrett" | "Garry" | "Garth" | "Gary" | "Gaston" | "Gavin" | "Gayle" 
	| "Gaylord" | "Genaro" | "Gene" | "Geoffrey" | "George" | "Gerald" | "Geraldo" | "Gerard" | "Gerardo" | "German" | "Gerry" | "Gil" 
	| "Gilbert" | "Gilberto" | "Gino" | "Giovanni" | "Giuseppe" | "Glen" | "Glenn" | "Gonzalo" | "Gordon" | "Grady" | "Graham" | "Graig" 
	| "Grant" | "Granville" | "Greg" | "Gregg" | "Gregorio" | "Gregory" | "Grover" | "Guadalupe" | "Guillermo" | "Gus" | "Gustavo" 
	| "Guy" | "Hai" | "Hal" | "Hank" | "Hans" | "Harlan" | "Harland" | "Harley" | "Harold" | "Harris" | "Harrison" | "Harry" | "Harvey" 
	| "Hassan" | "Hayden" | "Haywood" | "Heath" | "Hector" | "Henry" | "Herb" | "Herbert" | "Heriberto" | "Herman" | "Herschel" 
	| "Hershel" | "Hilario" | "Hilton" | "Hipolito" | "Hiram" | "Hobert" | "Hollis" | "Homer" | "Hong" | "Horace" | "Horacio" | "Hosea" 
	| "Houston" | "Howard" | "Hoyt" | "Hubert" | "Huey" | "Hugh" | "Hugo" | "Humberto" | "Hung" | "Hunter" | "Hyman" | "Ian" | "Ignacio" 
	| "Ike" | "Ira" | "Irvin" | "Irving" | "Irwin" | "Isaac" | "Isaiah" | "Isaias" | "Isiah" | "Isidro" | "Ismael" | "Israel" | "Isreal" 
	| "Issac" | "Ivan" | "Ivory" | "Jacinto" | "Jack" | "Jackie" | "Jackson" | "Jacob" | "Jacques" | "Jae" | "Jaime" | "Jake" | "Jamaal" 
	| "Jamal" | "Jamar" | "Jame" | "Jamel" | "James" | "Jamey" | "Jamie" | "Jamison" | "Jan" | "Jared" | "Jarod" | "Jarred" | "Jarrett" 
	| "Jarrod" | "Jarvis" | "Jason" | "Jasper" | "Javier" | "Jay" | "Jayson" | "Jc" | "Jean" | "Jed" | "Jeff" | "Jefferey" | "Jefferson" 
	| "Jeffery" | "Jeffrey" | "Jeffry" | "Jerald" | "Jeramy" | "Jere" | "Jeremiah" | "Jeremy" | "Jermaine" | "Jerold" | "Jerome" 
	| "Jeromy" | "Jerrell" | "Jerrod" | "Jerrold" | "Jerry" | "Jess" | "Jesse" | "Jessie" | "Jesus" | "Jewel" | "Jewell" | "Jim" 
	| "Jimmie" | "Jimmy" | "Joan" | "Joaquin" | "Jody" | "Joe" | "Joel" | "Joesph" | "Joey" | "John" | "Johnathan" | "Johnathon" 
	| "Johnie" | "Johnnie" | "Johnny" | "Johnson" | "Jon" | "Jonah" | "Jonas" | "Jonathan" | "Jonathon" | "Jordan" | "Jordon" | "Jorge" 
	| "Jose" | "Josef" | "Joseph" | "Josh" | "Joshua" | "Josiah" | "Jospeh" | "Josue" | "Juan" | "Jude" | "Judson" | "Jules" | "Julian" 
	| "Julio" | "Julius" | "Junior" | "Justin" | "Kareem" | "Karl" | "Kasey" | "Keenan" | "Keith" | "Kelley" | "Kelly" | "Kelvin" | "Ken" 
	| "Kendall" | "Kendrick" | "Keneth" | "Kenneth" | "Kennith" | "Kenny" | "Kent" | "Kenton" | "Kermit" | "Kerry" | "Keven" | "Kevin" 
	| "Kieth" | "Kim" | "King" | "Kip" | "Kirby" | "Kirk" | "Korey" | "Kory" | "Kraig" | "Kris" | "Kristofer" | "Kristopher" | "Kurt" 
	| "Kurtis" | "Kyle" | "Lacy" | "Lamar" | "Lamont" | "Lance" | "Landon" | "Lane" | "Lanny" | "Larry" | "Lauren" | "Laurence" 
	| "Lavern" | "Laverne" | "Lawerence" | "Lawrence" | "Lazaro" | "Leandro" | "Lee" | "Leif" | "Leigh" | "Leland" | "Lemuel" | "Len" 
	| "Lenard" | "Lenny" | "Leo" | "Leon" | "Leonard" | "Leonardo" | "Leonel" | "Leopoldo" | "Leroy" | "Les" | "Lesley" | "Leslie" 
	| "Lester" | "Levi" | "Lewis" | "Lincoln" | "Lindsay" | "Lindsey" | "Lino" | "Linwood" | "Lionel" | "Lloyd" | "Logan" | "Lon" 
	| "Long" | "Lonnie" | "Lonny" | "Loren" | "Lorenzo" | "Lou" | "Louie" | "Louis" | "Lowell" | "Loyd" | "Lucas" | "Luciano" | "Lucien" 
	| "Lucio" | "Lucius" | "Luigi" | "Luis" | "Luke" | "Lupe" | "Luther" | "Lyle" | "Lyman" | "Lyndon" | "Lynn" | "Lynwood" | "Mac"
	| "Mack" | "Major" | "Malcolm" | "Malcom" | "Malik" | "Man" | "Manual" | "Manuel" | "Marc" | "Marcel" | "Marcelino" | "Marcellus" 
	| "Marcelo" | "Marco" | "Marcos" | "Marcus" | "Margarito" | "Maria" | "Mariano" | "Mario" | "Marion" | "Mark" | "Markus" | "Marlin" 
	| "Marlon" | "Marquis" | "Marshall" | "Martin" | "Marty" | "Marvin" | "Mary" | "Mason" | "Mathew" | "Matt" | "Matthew" | "Maurice" 
	| "Mauricio" | "Mauro" | "Max" | "Maximo" | "Maxwell" | "Maynard" | "Mckinley" | "Mel" | "Melvin" | "Merle" | "Merlin" | "Merrill" 
	| "Mervin" | "Micah" | "Michael" | "Michal" | "Michale" | "Micheal" | "Michel" | "Mickey" | "Miguel" | "Mike" | "Mikel" | "Milan" 
	| "Miles" | "Milford" | "Millard" | "Milo" | "Milton" | "Minh" | "Miquel" | "Mitch" | "Mitchel" | "Mitchell" | "Modesto" | "Mohamed" 
	| "Mohammad" | "Mohammed" | "Moises" | "Monroe" | "Monte" | "Monty" | "Morgan" | "Morris" | "Morton" | "Mose" | "Moses" | "Moshe" 
	| "Murray" | "Myles" | "Myron" | "Napoleon" | "Nathan" | "Nathanael" | "Nathanial" | "Nathaniel" | "Neal" | "Ned" | "Neil" 
	| "Nelson" | "Nestor" | "Neville" | "Newton" | "Nicholas" | "Nick" | "Nickolas" | "Nicky" | "Nicolas" | "Nigel" | "Noah" | "Noble" 
	| "Noe" | "Noel" | "Nolan" | "Norbert" | "Norberto" | "Norman" | "Normand" | "Norris" | "Numbers" | "Octavio" | "Odell" | "Odis" 
	| "Olen" | "Olin" | "Oliver" | "Ollie" | "Omar" | "Omer" | "Oren" | "Orlando" | "Orval" | "Orville" | "Oscar" | "Osvaldo" 
	| "Oswaldo" | "Otha" | "Otis" | "Otto" | "Owen" | "Pablo" | "Palmer" | "Paris" | "Parker" | "Pasquale" | "Pat" | "Patricia" 
	| "Patrick" | "Paul" | "Pedro" | "Percy" | "Perry" | "Pete" | "Peter" | "Phil" | "Philip" | "Phillip" | "Pierre" | "Porfirio" 
	| "Porter" | "Preston" | "Prince" | "Quentin" | "Quincy" | "Quinn" | "Quintin" | "Quinton" | "Rafael" | "Raleigh" | "Ralph" 
	| "Ramiro" | "Ramon" | "Randal" | "Randall" | "Randell" | "Randolph" | "Randy" | "Raphael" | "Rashad" | "Raul" | "Ray" | "Rayford" 
	| "Raymon" | "Raymond" | "Raymundo" | "Reed" | "Refugio" | "Reggie" | "Reginald" | "Reid" | "Reinaldo" | "Renaldo" | "Renato" 
	| "Rene" | "Reuben" | "Rex" | "Rey" | "Reyes" | "Reynaldo" | "Rhett" | "Ricardo" | "Rich" | "Richard" | "Richie" | "Rick" | "Rickey" 
	| "Rickie" | "Ricky" | "Rico" | "Rigoberto" | "Riley" | "Rob" | "Robbie" | "Robby" | "Robert" | "Roberto" | "Robin" | "Robt" 
	| "Rocco" | "Rocky" | "Rod" | "Roderick" | "Rodger" | "Rodney" | "Rodolfo" | "Rodrick" | "Rodrigo" | "Rogelio" | "Roger" | "Roland" 
	| "Rolando" | "Rolf" | "Rolland" | "Roman" | "Romeo" | "Ron" | "Ronald" | "Ronnie" | "Ronny" | "Roosevelt" | "Rory" | "Rosario" 
	| "Roscoe" | "Rosendo" | "Ross" | "Roy" | "Royal" | "Royce" | "Ruben" | "Rubin" | "Rudolf" | "Rudolph" | "Rudy" | "Rueben" | "Rufus" 
	| "Rupert" | "Russ" | "Russel" | "Russell" | "Rusty" | "Ryan" | "Sal" | "Salvador" | "Salvatore" | "Sam" | "Sammie" | "Sammy" 
	| "Samual" | "Samuel" | "Sandy" | "Sanford" | "Sang" | "Santiago" | "Santo" | "Santos" | "Saul" | "Scot" | "Scott" | "Scottie" 
	| "Scotty" | "Sean" | "Sebastian" | "Sergio" | "Seth" | "Seymour" | "Shad" | "Shane" | "Shannon" | "Shaun" | "Shawn" | "Shayne" 
	| "Shelby" | "Sheldon" | "Shelton" | "Sherman" | "Sherwood" | "Shirley" | "Shon" | "Sid" | "Sidney" | "Silas" | "Simon" | "Sol" 
	| "Solomon" | "Son" | "Sonny" | "Spencer" | "Stacey" | "Stacy" | "Stan" | "Stanford" | "Stanley" | "Stanton" | "Stefan" | "Stephan" 
	| "Stephen" | "Sterling" | "Steve" | "Steven" | "Stevie" | "Stewart" | "Stuart" | "Sung" | "Sydney" | "Sylvester" | "Tad" | "Tanner" 
	| "Taylor" | "Ted" | "Teddy" | "Teodoro" | "Terence" | "Terrance" | "Terrell" | "Terrence" | "Terry" | "Thad" | "Thaddeus" | "Thanh" 
	| "Theo" | "Theodore" | "Theron" | "Thomas" | "Thurman" | "Tim" | "Timmy" | "Timothy" | "Titus" | "Tobias" | "Toby" | "Tod" | "Todd" 
	| "Tom" | "Tomas" | "Tommie" | "Tommy" | "Toney" | "Tony" | "Tory" | "Tracey" | "Tracy" | "Travis" | "Trent" | "Trenton" | "Trevor" 
	| "Trey" | "Trinidad" | "Tristan" | "Troy" | "Truman" | "Tuan" | "Ty" | "Tyler" | "Tyree" | "Tyrell" | "Tyron" | "Tyrone" | "Tyson" 
	| "Ulysses" | "Val" | "Valentin" | "Valentine" | "Van" | "Vance" | "Vaughn" | "Vern" | "Vernon" | "Vicente" | "Victor" | "Vince" 
	| "Vincent" | "Vincenzo" | "Virgil" | "Virgilio" | "Vito" | "Von" | "Wade" | "Waldo" | "Walker" | "Wallace" | "Wally" | "Walter" 
	| "Walton" | "Ward" | "Warner" | "Warren" | "Waylon" | "Wayne" | "Weldon" | "Wendell" | "Werner" | "Wes" | "Wesley" | "Weston" 
	| "Whitney" | "Wilber" | "Wilbert" | "Wilbur" | "Wilburn" | "Wiley" | "Wilford" | "Wilfred" | "Wilfredo" | "Will" | "Willard" 
	| "William" | "Williams" | "Willian" | "Willie" | "Willis" | "Willy" | "Wilmer" | "Wilson" | "Wilton" | "Winford" | "Winfred" 
	| "Winston" | "Wm" | "Woodrow" | "Wyatt" | "Xavier" | "Yong" | "Young" | "Zachariah" | "Zachary" | "Zachery" | "Zack" | "Zackary" 
	| "Zane"
;

%resource female-first-name:
	"Abbey" | "Abbie" | "Adah" | "Adelaida" | "Adelaide" | "Adrian" | "Adriane" | "Afton" | "Ai" | "Albertina" | "Alecia" | "Alesha" 
	| "Clotilde" | "Clyde" | "Coleen" | "Colene" | "Coletta" | "Collette" | "Concha" | "Contessa" | "Cora" | "Coralie" | "Corene" 
	| "Ladonna" | "Lael" | "Lai" | "Lakeesha" | "Lakendra" | "Lakiesha" | "Lakisha" | "Lala" | "Lamonica" | "Lan" | "Lana" | "Lane" 
	| "Waneta" | "Wava" | "Wendie" | "Wendy" | "Whitney" | "Wilda" | "Wilhemina" | "Willette" | "Willia" | "Willow" | "Winifred" 
	| "Robyn" | "Rochel" | "Rochell" | "Rochelle" | "Roma" | "Romaine" | "Ronald" | "Ronna" | "Rory" | "Rosa" | "Rosalee" | "Rosalina" 
	| "Clarence" | "Claretta" | "Claris" | "Clarissa" | "Claudette" | "Claudie" | "Clelia" | "Clementina" | "Clementine" | "Cleta" 
	| "Veronica" | "Versie" | "Veta" | "Vickey" | "Vicki" | "Vikki" | "Vina" | "Virgen" | "Virgie" | "Vivan" | "Viviana" | "Walter" 
	| "Michaele" | "Michel" | "Michelina" | "Michelle" | "Michiko" | "Mickie" | "Miesha" | "Migdalia" | "Miguelina" | "Mimi" | "Minerva" 
	| "Telma" | "Tempie" | "Teodora" | "Teresita" | "Terra" | "Tesha" | "Tessie" | "Thea" | "Theola" | "Theresia" | "Theressa" 
	| "Ingeborg" | "Ione" | "Irena" | "Irene" | "Irina" | "Iris" | "Irish" | "Irmgard" | "Isabel" | "Isabell" | "Isaura" | "Isela" 
	| "Cherry" | "Chieko" | "Chin" | "China" | "Chiquita" | "Chloe" | "Chong" | "Chris" | "Christa" | "Christal" | "Christel" 
	| "Layne" | "Leana" | "Leandra" | "Leanne" | "Lecia" | "Lee" | "Leeann" | "Leeanna" | "Leeanne" | "Leida" | "Leigh" | "Leighann" 
	| "Melodie" | "Melody" | "Melonie" | "Melva" | "Melvin" | "Melvina" | "Melynda" | "Mendy" | "Meredith" | "Merideth" | "Meridith" 
	| "Shanice" | "Shanon" | "Shanta" | "Shantel" | "Shaquana" | "Shara" | "Sharee" | "Sharen" | "Shari" | "Sharie" | "Sharleen" 
	| "Ludivina" | "Lue" | "Luetta" | "Luis" | "Luise" | "Lupe" | "Lyda" | "Lyndia" | "Lynne" | "Lynnette" | "Ma" | "Mabel" | "Machelle" 
	| "Margarett" | "Margarita" | "Margarite" | "Margart" | "Marge" | "Margeret" | "Margit" | "Margo" | "Margret" | "Margrett" 
	| "Lavelle" | "Lavenia" | "Lavera" | "Lavette" | "Lavona" | "Lavonda" | "Lavonia" | "Lawana" | "Lawanda" | "Lawrence" | "Layla" 
	| "Love" | "Lovetta" | "Loyce" | "Luana" | "Luann" | "Luanna" | "Luanne" | "Luciana" | "Lucie" | "Lucila" | "Lucy" | "Ludie" 
	| "Thersa" | "Thi" | "Thomasena" | "Thomasina" | "Tiana" | "Tiara" | "Tifany" | "Tiffanie" | "Tijuana" | "Tish" | "Toi" | "Tomiko" 
	| "Kristyn" | "Krysta" | "Krystin" | "Kyla" | "Kylee" | "Kym" | "Kymberly" | "Kyoko" | "Kyong" | "Kyra" | "Kyung" | "Lacie" 
	| "Eustolia" | "Eva" | "Evalyn" | "Evangelina" | "Evelin" | "Evelina" | "Eveline" | "Evia" | "Evie" | "Evon" | "Ewa" | "Fabiola" 
	| "Yetta" | "Yevette" | "Yi" | "Yoko" | "Yolande" | "Yolando" | "Yon" | "Yong" | "Yuk" | "Yulanda" | "Zandra" | "Zena" | "Zenia" 
	| "Kandra" | "Kanesha" | "Karena" | "Karey" | "Karina" | "Karine" | "Karla" | "Karleen" | "Karly" | "Karma" | "Karren" | "Karyl" 
	| "Jenette" | "Jenice" | "Jeniffer" | "Jenise" | "Jenna" | "Jenni" | "Jennine" | "Jeraldine" | "Jerilyn" | "Jesenia" | "Jesica" 
	| "Jocelyn" | "Joel" | "Joelle" | "Joellen" | "Joey" | "Johanna" | "Johna" | "Joie" | "Jolie" | "Jolyn" | "Jon" | "Jone" | "Jonell" 
	| "Ernestina" | "Eryn" | "Esmeralda" | "Esta" | "Estella" | "Estrella" | "Etha" | "Etta" | "Eugena" | "Eula" | "Euna" | "Eusebia" 
	| "Dorene" | "Doretha" | "Doria" | "Dorothea" | "Dortha" | "Dotty" | "Dovie" | "Drema" | "Drew" | "Drucilla" | "Dulce" | "Dung" 
	| "Patrice" | "Patricia" | "Patsy" | "Pauletta" | "Paz" | "Peggy" | "Perry" | "Peter" | "Philomena" | "Phuong" | "Phylis" | "Ping" 
	| "Tamar" | "Tamatha" | "Tambra" | "Tameika" | "Tamera" | "Tami" | "Tamisha" | "Tammi" | "Tammy" | "Tamra" | "Tandra" | "Taneka" 
	| "Arla" | "Arlena" | "Arletta" | "Arlette" | "Arlinda" | "Arline" | "Armandina" | "Arvilla" | "Ashanti" | "Ashlee" | "Ashlie" 
	| "Rowena" | "Rozella" | "Rubye" | "Rudy" | "Ruth" | "Rutha" | "Ruthann" | "Ruthie" | "Sabina" | "Sabine" | "Sade" | "Sage" 
	| "Latashia" | "Latia" | "Latoria" | "Latosha" | "Latoyia" | "Latrina" | "Laura" | "Laurena" | "Lauretta" | "Laurette" | "Lauryn" 
	| "Bettina" | "Bev" | "Beverley" | "Bibi" | "Birdie" | "Birgit" | "Blair" | "Bobbi" | "Bobette" | "Bonita" | "Branda" | "Brandee" 
	| "Kirsten" | "Kisha" | "Kittie" | "Kizzie" | "Kizzy" | "Klara" | "Kori" | "Krissy" | "Kristan" | "Kristi" | "Kristie" | "Kristine" 
	| "Sharmaine" | "Sharon" | "Sharri" | "Sharyl" | "Shauna" | "Shaunna" | "Shavon" | "Shavonne" | "Shawana" | "Shawanda" | "Shawanna" 
	| "Ming" | "Minh" | "Minna" | "Minnie" | "Minta" | "Miranda""Mireya" | "Miriam" | "Mirian" | "Mirta" | "Missy" | "Mitsue" | "Mitzie" 
	| "Coretta" | "Cori" | "Corine" | "Corliss" | "Corrie" | "Corrinne" | "Cortney" | "Courtney" | "Cris" | "Criselda" | "Cristy" 
	| "Polly" | "Porsche" | "Princess" | "Prudence" | "Pura" | "Queenie" | "Quiana" | "Quinn" | "Racheal" | "Rachele" | "Raelene" 
	| "Lili" | "Lilia" | "Lilian" | "Lilla" | "Lilliam" | "Lillian" | "Lilliana" | "Linda" | "Lindsay" | "Linh" | "Linn" | "Linsey" 
	| "Tanesha" | "Tara" | "Taren" | "Tari" | "Tarsha" | "Tashina" | "Tasia" | "Tatum" | "Tawanda" | "Tawanna" | "Taylor" | "Tegan" 
	| "Omega" | "Opal" | "Oretha" | "Orpha" | "Otelia" | "Otha" | "Ozie" | "Page" | "Pamella" | "Pamula" | "Pandora" | "Pat" | "Patria" 
	| "Delinda" | "Della" | "Delmy" | "Deloise" | "Delora" | "Delpha" | "Delsie" | "Delta" | "Demetrice" | "Deneen" | "Denice" 
	| "Brandon" | "Brandy" | "Breana" | "Breann" | "Bree" | "Brian" | "Briana" | "Brianna" | "Brianne" | "Britany" | "Britney" 
	| "Dione" | "Dixie" | "Dolores" | "Dominica" | "Dominique" | "Dona" | "Donna" | "Donnetta" | "Donnette" | "Donya" | "Doreen" 
	| "Neoma" | "Neomi" | "Nereida" | "Neta" | "Ngoc" | "Nichelle" | "Nichol" | "Nicola" | "Nicolasa" | "Nicole" | "Nicolette" 
	| "Felipa" | "Fern" | "Fernanda" | "Fidela" | "Fiona" | "Flavia" | "Fleta" | "Flora" | "Florene" | "Floria" | "Florida" | "Florinda" 
	| "Eleanore" | "Elenora" | "Elfreda" | "Elidia" | "Elise" | "Eliz" | "Eliza" | "Elizabeth" | "Elizebeth" | "Elke" | "Ellan" 
	| "Shawn" | "Shawnda" | "Shawnee" | "Shay" | "Shea" | "Sheila" | "Shela" | "Shelba" | "Shelby" | "Shelia" | "Shella" | "Shena" 
	| "Jong" | "Jonna" | "Jose" | "Josefina" | "Josefine" | "Joselyn" | "Joseph" | "Josephina" | "Josephine" | "Jovan" | "Jovita" 
	| "Amee" | "Amelia" | "Ami" | "Amiee" | "Ammie" | "Ana" | "Anabel" | "Anastasia" | "Andra" | "Andre" | "Andrea" | "Andree" 
	| "Macy" | "Madalene" | "Madaline" | "Madeleine" | "Madison" | "Madonna" | "Mafalda" | "Magaly" | "Magaret" | "Magda" | "Magdalena" 
	| "Shenika" | "Shera" | "Sheree" | "Sherell" | "Sherill" | "Sherly" | "Sherrell" | "Sherrill" | "Shery" | "Sheryl" | "Shiloh" 
	| "Rebekah" | "Reena" | "Refugio" | "Regena" | "Regenia" | "Reginia" | "Reiko" | "Reita" | "Rema" | "Rena" | "Renda" | "Rene" 
	| "Debora" | "Deborah" | "Debrah" | "Dedra" | "Deedee" | "Deedra" | "Deena" | "Deetta" | "Delana" | "Delicia" | "Delila" | "Delilah" 
	| "Gisela" | "Giuseppina" | "Glayds" | "Glenn" | "Glenna" | "Glennie" | "Glinda" | "Gloria" | "Glynis" | "Golda" | "Graciela" 
	| "Hye" | "Ida" | "Idella" | "Ila" | "Ilda" | "Ileen" | "Ilene" | "Illa" | "Ilona" | "Iluminada" | "Imelda" | "India" | "Inga" 
	| "Justina" | "Kaci" | "Kacie" | "Kacy" | "Kaila" | "Kaitlin" | "Kallie" | "Kam" | "Kami" | "Kamilah" | "Kandace" | "Kandi" 
	| "Fredericka" | "Frida" | "Gala" | "Gale" | "Galina" | "Garnet" | "Garnett" | "Gayla" | "Gaynell" | "Gearldine" | "Genesis" 
	| "Danette" | "Dania" | "Danielle" | "Danna" | "Danuta" | "Danyel" | "Daphne" | "Darby" | "Darci" | "Darcie" | "Darcy" | "Darla" 
	| "Joy" | "Joyce" | "Joycelyn" | "Judith" | "Julian" | "Julie" | "Julienne" | "Julieta" | "Julietta" | "Julio" | "Julissa" | "June" 
	| "Meagan" | "Meaghan" | "Meda" | "Meg" | "Meggan" | "Meghann" | "Melani" | "Melania" | "Melba" | "Melda" | "Melisa" | "Melissia" 
	| "Moira" | "Mollie" | "Monet" | "Monserrate" | "Moon" | "Moriah" | "Mozell" | "Mozella" | "Muriel" | "Myong" | "Myra" | "Myriam" 
	| "Marylin" | "Maryln" | "Marylou" | "Maryrose" | "Mathilda" | "Maya" | "Maybelle" | "Maye" | "Mayme" | "Mayra" | "Mckenzie" 
	| "Marguerita" | "Margy" | "Marhta" | "Mariah" | "Mariann" | "Mariella" | "Marietta" | "Marilee" | "Marin" | "Marina" | "Marisa" 
	| "Apolonia" | "Ara" | "Araceli" | "Aracelis" | "Ardelia" | "Ardelle" | "Ardis" | "Argentina" | "Ariane" | "Arianna" | "Ariel" 
	| "Leila" | "Leilani" | "Leisa" | "Lenna" | "Leo" | "Leoma" | "Leon" | "Leonie" | "Leora" | "Lera" | "Lesha" | "Leslee" | "Leslie" 
	| "Kelle" | "Kellee" | "Kelli" | "Kelsi" | "Kena" | "Kendal" | "Kenneth" | "Kerrie" | "Kesha" | "Keturah" | "Khadijah" | "Kiana" 
	| "Jacque" | "Jacquelin" | "Jacqueline" | "Jacquelyne" | "Jacquelynn" | "Jacquetta" | "Jacqulyn" | "Jadwiga" | "Jalisa" | "Jamey" 
	| "Shonda" | "Shonna" | "Shu" | "Sidney" | "Sierra" | "Sigrid" | "Sina" | "Sirena" | "Siu" | "Sol" | "Solange" | "Son" | "Soon" 
	| "Tommy" | "Tommye" | "Tonette" | "Tonisha" | "Torri" | "Torrie" | "Tory" | "Tosha" | "Toshiko" | "Tracey" | "Tran" | "Treasa" 
	| "Carmelia" | "Carmelina" | "Carmen" | "Carmina" | "Carol" | "Carola" | "Caroline" | "Carolyne" | "Carolynn" | "Carrol" | "Carroll" 
	| "Denise" | "Denna" | "Denny" | "Denyse" | "Despina" | "Devona" | "Devora" | "Devorah" | "Diamond" | "Dian" | "Dianna" | "Digna" 
	| "Iva" | "Ivana" | "Ivelisse" | "Ivette" | "Ivory" | "Jacalyn" | "Jack" | "Jackelyn" | "Jackie" | "Jacklyn" | "Jackqueline" 
	| "Renee" | "Renita" | "Renna" | "Ressie" | "Reta" | "Reva" | "Rheba" | "Rhiannon" | "Rhonda" | "Ria" | "Rikki" | "Rima" | "Rita" 
	| "Valerie" | "Valery" | "Vallie" | "Valrie" | "Vanesa" | "Velia" | "Venetta" | "Venice" | "Venita" | "Vera" | "Verda" | "Verlene" 
	| "Marquita" | "Marth" | "Martin" | "Marty" | "Marvel" | "Marx" | "Mary" | "Maryanna" | "Maryanne" | "Maryetta" | "Marylee" 
	| "Gerri" | "Gerry" | "Gertha" | "Gertude" | "Ghislaine" | "Gianna" | "Gidget" | "Gigi" | "Gilberte" | "Gillian" | "Gina" | "Ginger" 
	| "Fonda" | "Francene" | "Frances" | "Francie" | "Francina" | "Francis" | "Francisco" | "Frankie" | "Freddie" | "Frederica" 
	| "Christena" | "Christia" | "Christina" | "Christine" | "Christopher" | "Ciera" | "Cindie" | "Cinthia" | "Claire" | "Clare" 
	| "Myrta" | "Myrtice" | "Myrtle" | "Nada" | "Nadene" | "Nakia" | "Nam" | "Nan" | "Nancee" | "Nanci" | "Nancie" | "Nanette" | "Naomi" 
	| "September" | "Serena" | "Serita" | "Shaina" | "Shalanda" | "Shamika" | "Shanae" | "Shandi" | "Shaneka" | "Shanel" | "Shanell" 
	| "Narcisa" | "Natalia" | "Natisha" | "Natosha" | "Neda" | "Neely" | "Neida" | "Nelia" | "Nell" | "Nella" | "Nellie" | "Nelly" 
	| "Magdalene" | "Magnolia" | "Mai" | "Maida" | "Maira" | "Maire" | "Majorie" | "Makeda" | "Malia" | "Malika" | "Malinda" | "Mallie" 
	| "Anitra" | "Annabell" | "Annabelle" | "Anneliese" | "Annemarie" | "Annetta" | "Annette" | "Annika" | "Antonia" | "Antonio" 
	| "Rafaela" | "Raguel" | "Raina" | "Ramona" | "Randa" | "Ranee" | "Rashida" | "Raven" | "Rebbeca" | "Rebbecca" | "Rebeca" 
	| "Darnell" | "Dawn" | "Daysi" | "Deadra" | "Dean" | "Deana" | "Deandra" | "Deandrea" | "Deane" | "Deanne" | "Debbra" | "Debi" 
	| "Jayna" | "Jeane" | "Jeanene" | "Jeanice" | "Jeanine" | "Jeanna" | "Jeanne" | "Jeannie" | "Jeffie" | "Jene" | "Jenee" | "Jenelle" 
	| "Assunta" | "Asuncion" | "Audie" | "Audrea" | "Audria" | "Audrie" | "Augusta" | "Avelina" | "Avery" | "Avis" | "Avril" | "Ayako" 
	| "Mammie" | "Man" | "Mandi" | "Mandy" | "Maragret" | "Marcelene" | "Marcell" | "Marcia" | "Marcie" | "Marcy" | "Mardell" | "Maren"
	| "Brittany" | "Bronwyn" | "Bruna" | "Brunilda" | "Bryanna" | "Buffy" | "Burma" | "Caitlin" | "Calista" | "Candie" | "Candis" 
	| "Obdulia" | "Octavia" | "Ofelia" | "Ola" | "Olene" | "Oleta" | "Olga" | "Olimpia" | "Olinda" | "Oliva" | "Olivia" | "Olympia" 
	| "Crysta" | "Cyrstal" | "Cythia" | "Dahlia" | "Daine" | "Dalila" | "Dallas" | "Damaris" | "Dan" | "Dana" | "Danae" | "Danelle" 
	| "Grisel" | "Gudrun" | "Gwenda" | "Ha" | "Halley" | "Hallie" | "Hana" | "Hang" | "Hannah" | "Harriett" | "Hattie" | "Haydee" 
	| "Leticia" | "Lettie" | "Letty" | "Lexie" | "Lezlie" | "Liana" | "Libbie" | "Libby" | "Librada" | "Lidia" | "Lien" | "Lila" 
	| "Sanora" | "Santa" | "Sarai" | "Saran" | "Sarina" | "Sasha" | "Saturnina" | "Saundra" | "Scarlet" | "Season" | "Sena" 
	| "Zenobia" | "Zina" | "Zoe" | "Zulema"
;

%resource last-name:
	"Aaron" | "Abbott" | "Abel" | "Abernathy" | "Abraham" | "Abrams" | "Acevedo" | "Ackerman" | "Acosta" | "Adair" | "Adams" | "Addison" 
	| "Adkins" | "Aguilar" | "Aguirre" | "Akers" | "Akins" | "Albert" | "Albright" | "Aldrich" | "Aldridge" | "Alexander" | "Alfaro" 
	| "Alford" | "Ali" | "Allen" | "Allison" | "Allred" | "Alston" | "Alvarado" | "Alvarez" | "Ambrose" | "Ames" | "Amos" | "Anaya" 
	| "Andersen" | "Anderson" | "Andrade" | "Andrews" | "Anthony" | "Aragon" | "Archer" | "Arellano" | "Arias" | "Armstrong" | "Arnold" 
	| "Arredondo" | "Arrington" | "Arroyo" | "Arthur" | "Ash" | "Ashby" | "Ashley" | "Askew" | "Atkins" | "Atkinson" | "Atwood" 
	| "Austin" | "Avery" | "Avila" | "Ayala" | "Ayers" | "Babb" | "Babcock" | "Baca" | "Bacon" | "Baez" | "Bailey" | "Bain" | "Baird" 
	| "Baker" | "Baldwin" | "Ball" | "Ballard" | "Banks" | "Barajas" | "Barber" | "Barker" | "Barlow" | "Barnard" | "Barnes" | "Barnett" 
	| "Barnhart" | "Barr" | "Barrera" | "Barrett" | "Barron" | "Barrow" | "Barry" | "Bartlett" | "Bartley" | "Barton" | "Bass" 
	| "Bassett" | "Bateman" | "Bates" | "Battle" | "Bauer" | "Bautista" | "Baxter" | "Beach" | "Beal" | "Bean" | "Beard" | "Bearden" 
	| "Beasley" | "Beatty" | "Beaver" | "Beck" | "Becker" | "Begay" | "Belanger" | "Belcher" | "Bell" | "Bellamy" | "Beltran" 
	| "Benavides" | "Bender" | "Benitez" | "Benjamin" | "Bennett" | "Benoit" | "Benson" | "Bentley" | "Benton" | "Berg" | "Berger" 
	| "Bergeron" | "Bergman" | "Bermudez" | "Bernal" | "Bernard" | "Berry" | "Best" | "Betts" | "Biggs" | "Billings" | "Bingham" 
	| "Bird" | "Bishop" | "Black" | "Blackburn" | "Blackman" | "Blackmon" | "Blackwell" | "Blair" | "Blake" | "Blanchard" | "Blanco" 
	| "Bland" | "Blankenship" | "Blanton" | "Bledsoe" | "Blevins" | "Bliss" | "Block" | "Bloom" | "Blount" | "Blue" | "Boggs" | "Bolden" 
	| "Bolton" | "Bond" | "Bonds" | "Bonilla" | "Bonner" | "Booker" | "Boone" | "Booth" | "Boston" | "Boswell" | "Bouchard" | "Boucher" 
	| "Boudreaux" | "Bourgeois" | "Bowden" | "Bowen" | "Bower" | "Bowers" | "Bowles" | "Bowling" | "Bowman" | "Boyce" | "Boyd" | "Boyer" 
	| "Boykin" | "Boyle" | "Bradford" | "Bradley" | "Bradshaw" | "Brady" | "Bragg" | "Branch" | "Brand" | "Brandon" | "Brandt" 
	| "Brantley" | "Braswell" | "Braun" | "Bravo" | "Bray" | "Brennan" | "Brewer" | "Brewster" | "Bridges" | "Briggs" | "Bright" 
	| "Britt" | "Britton" | "Brock" | "Brooks" | "Broussard" | "Brown" | "Browne" | "Browning" | "Bruce" | "Bruner" | "Bruno" 
	| "Brunson" | "Bryan" | "Bryant" | "Bryson" | "Buchanan" | "Buck" | "Buckley" | "Buckner" | "Bullard" | "Bullock" | "Bunch" 
	| "Burch" | "Burger" | "Burgess" | "Burgos" | "Burke" | "Burkett" | "Burks" | "Burnett" | "Burnette" | "Burns" | "Burr" | "Burrell" 
	| "Burris" | "Burroughs" | "Burt" | "Burton" | "Busby" | "Bush" | "Butcher" | "Butler" | "Butts" | "Byers" | "Bynum" | "Byrd" 
	| "Byrne" | "Cabrera" | "Cahill" | "Cain" | "Calderon" | "Caldwell" | "Calhoun" | "Call" | "Callahan" | "Calloway" | "Calvert" 
	| "Camacho" | "Cameron" | "Camp" | "Campbell" | "Campos" | "Cannon" | "Cano" | "Cantrell" | "Cantu" | "Capps" | "Cardenas" | "Carey" 
	| "Carlisle" | "Carlson" | "Carlton" | "Carmichael" | "Carney" | "Caron" | "Carpenter" | "Carr" | "Carrier" | "Carrillo" | "Carroll" 
	| "Carson" | "Carter" | "Cartwright" | "Carver" | "Case" | "Casey" | "Cash" | "Cassidy" | "Castaneda" | "Castillo" | "Castle" 
	| "Castro" | "Cates" | "Caudill" | "Cervantes" | "Chacon" | "Chamberlain" | "Chambers" | "Champagne" | "Champion" | "Chan" 
	| "Chandler" | "Chaney" | "Chang" | "Chapman" | "Chappell" | "Charles" | "Chase" | "Chatman" | "Chavez" | "Chen" | "Cherry" 
	| "Childers" | "Childress" | "Childs" | "Chin" | "Cho" | "Choi" | "Christensen" | "Christian" | "Christiansen" | "Christie" 
	| "Christopher" | "Chu" | "Chung" | "Church" | "Cisneros" | "Clark" | "Clarke" | "Clay" | "Clayton" | "Clement" | "Clements" 
	| "Clemons" | "Cleveland" | "Clifford" | "Clifton" | "Cline" | "Clinton" | "Coates" | "Cobb" | "Cochran" | "Cody" | "Coffey" 
	| "Coffman" | "Cohen" | "Coker" | "Colbert" | "Cole" | "Coleman" | "Coley" | "Collier" | "Collins" | "Colon" | "Colvin" | "Combs" 
	| "Comer" | "Compton" | "Conklin" | "Conley" | "Conn" | "Connell" | "Connelly" | "Conner" | "Connolly" | "Connor" | "Connors" 
	| "Conrad" | "Contreras" | "Conway" | "Cook" | "Cooke" | "Cooley" | "Coon" | "Cooper" | "Cope" | "Copeland" | "Corbett" | "Corbin" 
	| "Corcoran" | "Cordero" | "Cordova" | "Corley" | "Cormier" | "Cornelius" | "Cornell" | "Cornett" | "Corona" | "Coronado" | "Correa" 
	| "Cortes" | "Cortez" | "Costa" | "Costello" | "Cote" | "Cotton" | "Couch" | "Coulter" | "Courtney" | "Covington" | "Cowan" | "Cox" 
	| "Crabtree" | "Craft" | "Craig" | "Crain" | "Cramer" | "Crandall" | "Crane" | "Crawford" | "Crenshaw" | "Crews" | "Crocker" 
	| "Crockett" | "Crosby" | "Cross" | "Crouch" | "Crow" | "Crowder" | "Crowe" | "Crowell" | "Crowley" | "Crum" | "Crump" | "Cruz" 
	| "Cuevas" | "Cullen" | "Culver" | "Cummings" | "Cummins" | "Cunningham" | "Curran" | "Currie" | "Curry" | "Curtis" | "Dahl" 
	| "Dailey" | "Dale" | "Daley" | "Dalton" | "Daly" | "Daniel" | "Daniels" | "Darby" | "Darden" | "Darling" | "Darnell" | "Daugherty" 
	| "Davenport" | "David" | "Davidson" | "Davies" | "Davila" | "Davis" | "Davison" | "Dawkins" | "Dawson" | "Day" | "Deal" | "Dean" 
	| "Decker" | "Dejesus" | "Delacruz" | "Delaney" | "Delarosa" | "Deleon" | "Delgado" | "Delong" | "Dempsey" | "Dennis" | "Dennison" 
	| "Denny" | "Denton" | "Devine" | "Dewitt" | "Diamond" | "Diaz" | "Dick" | "Dickens" | "Dickerson" | "Dickey" | "Dickinson" 
	| "Dickson" | "Diggs" | "Dill" | "Dillard" | "Dillon" | "Dixon" | "Dobson" | "Dodd" | "Dodge" | "Dodson" | "Doherty" | "Dolan" 
	| "Dominguez" | "Donahue" | "Donaldson" | "Donnelly" | "Donovan" | "Dooley" | "Doran" | "Dorsey" | "Doss" | "Dotson" | "Doty" 
	| "Dougherty" | "Douglas" | "Dove" | "Dow" | "Dowdy" | "Downey" | "Downing" | "Downs" | "Doyle" | "Drake" | "Draper" | "Drew" 
	| "Driscoll" | "Driver" | "Drummond" | "Duarte" | "Dubois" | "Dudley" | "Duffy" | "Dugan" | "Duke" | "Dukes" | "Dumas" | "Dunbar" 
	| "Duncan" | "Dunham" | "Dunlap" | "Dunn" | "Dupree" | "Duran" | "Durham" | "Dutton" | "Duvall" | "Dwyer" | "Dye" | "Dyer" | "Earl" 
	| "Early" | "Easley" | "Eason" | "Eastman" | "Eaton" | "Echols" | "Eddy" | "Edmonds" | "Edwards" | "Egan" | "Elder" | "Eldridge" 
	| "Elkins" | "Elliot" | "Elliott" | "Ellis" | "Ellison" | "Elmore" | "Emerson" | "Emery" | "Engel" | "England" | "Engle" | "English" 
	| "Enriquez" | "Epps" | "Erickson" | "Ervin" | "Erwin" | "Escobar" | "Esparza" | "Espinosa" | "Espinoza" | "Esposito" | "Esquivel" 
	| "Estes" | "Estrada" | "Eubanks" | "Evans" | "Everett" | "Ewing" | "Fair" | "Farley" | "Farmer" | "Farr" | "Farrell" | "Farris" 
	| "Faulk" | "Faulkner" | "Feldman" | "Feliciano" | "Felix" | "Felton" | "Fenton" | "Ferguson" | "Fernandez" | "Ferreira" | "Ferrell" 
	| "Ferris" | "Field" | "Fields" | "Figueroa" | "Finch" | "Fink" | "Finley" | "Finn" | "Fischer" | "Fish" | "Fisher" | "Fitch" 
	| "Fitzgerald" | "Fitzpatrick" | "Flanagan" | "Fleming" | "Fletcher" | "Flint" | "Flood" | "Flores" | "Flowers" | "Floyd" | "Flynn" 
	| "Foley" | "Fontenot" | "Foote" | "Forbes" | "Ford" | "Foreman" | "Forrest" | "Foster" | "Fountain" | "Fournier" | "Fowler" | "Fox" 
	| "Francis" | "Franco" | "Frank" | "Franklin" | "Franks" | "Fraser" | "Frazier" | "Frederick" | "Freeman" | "French" | "Frey" 
	| "Friedman" | "Friend" | "Fritz" | "Frost" | "Fry" | "Frye" | "Fuentes" | "Fuller" | "Fulton" | "Funk" | "Gabriel" | "Gage" 
	| "Gagne" | "Gagnon" | "Gaines" | "Galindo" | "Gallagher" | "Gallegos" | "Gallo" | "Galloway" | "Galvan" | "Gamble" | "Garcia" 
	| "Gardner" | "Garland" | "Garner" | "Garrett" | "Garrison" | "Gary" | "Garza" | "Gaston" | "Gates" | "Gay" | "Gee" | "Geiger" 
	| "Gentry" | "George" | "Gibbons" | "Gibbs" | "Gibson" | "Gifford" | "Gilbert" | "Giles" | "Gill" | "Gillespie" | "Gilliam" 
	| "Gillis" | "Gilmore" | "Gipson" | "Givens" | "Glass" | "Gleason" | "Glenn" | "Glover" | "Goddard" | "Godfrey" | "Godwin" | "Goff" 
	| "Goins" | "Gold" | "Goldberg" | "Golden" | "Goldman" | "Goldsmith" | "Goldstein" | "Gomes" | "Gomez" | "Gonzales" | "Gonzalez" 
	| "Good" | "Goode" | "Goodman" | "Goodrich" | "Goodson" | "Goodwin" | "Gordon" | "Gore" | "Gorman" | "Goss" | "Gould" | "Grace" 
	| "Grady" | "Graham" | "Granger" | "Grant" | "Graves" | "Gray" | "Grayson" | "Green" | "Greenberg" | "Greene" | "Greenwood" 
	| "Greer" | "Gregg" | "Gregory" | "Griffin" | "Griffith" | "Griggs" | "Grimes" | "Grimm" | "Gross" | "Grove" | "Grover" | "Groves" 
	| "Grubbs" | "Guerra" | "Guerrero" | "Guevara" | "Guidry" | "Gunn" | "Gunter" | "Gustafson" | "Guthrie" | "Gutierrez" | "Guy" 
	| "Guzman" | "Haas" | "Hackett" | "Hadley" | "Hagan" | "Hagen" | "Hager" | "Hahn" | "Haines" | "Hairston" | "Hale" | "Haley" 
	| "Hall" | "Ham" | "Hamilton" | "Hamlin" | "Hamm" | "Hammer" | "Hammond" | "Hampton" | "Hancock" | "Hand" | "Haney" | "Hankins" 
	| "Hanks" | "Hanley" | "Hanna" | "Hannah" | "Hansen" | "Hanson" | "Harden" | "Hardin" | "Harding" | "Hardy" | "Hare" | "Hargrove" 
	| "Harmon" | "Harper" | "Harrell" | "Harrington" | "Harris" | "Harrison" | "Hart" | "Hartley" | "Hartman" | "Harvey" | "Haskins" 
	| "Hastings" | "Hatch" | "Hatcher" | "Hatfield" | "Hathaway" | "Hawk" | "Hawkins" | "Hayden" | "Hayes" | "Haynes" | "Hays" 
	| "Haywood" | "Head" | "Healy" | "Heard" | "Hearn" | "Heath" | "Hebert" | "Hedrick" | "Heller" | "Helms" | "Helton" | "Hemphill" 
	| "Henderson" | "Hendricks" | "Hendrickson" | "Hendrix" | "Henley" | "Henry" | "Hensley" | "Henson" | "Herbert" | "Herman" 
	| "Hernandez" | "Herndon" | "Herrera" | "Herring" | "Herrington" | "Herron" | "Hess" | "Hester" | "Hewitt" | "Hickey" | "Hickman" 
	| "Hicks" | "Higgins" | "Hightower" | "Hill" | "Hilliard" | "Hilton" | "Hines" | "Hinkle" | "Hinson" | "Hinton" | "Ho" | "Hobbs" 
	| "Hobson" | "Hodge" | "Hodges" | "Hoffman" | "Hogan" | "Hogue" | "Holbrook" | "Holcomb" | "Holden" | "Holder" | "Holland" 
	| "Holley" | "Holliday" | "Hollingsworth" | "Hollis" | "Holloway" | "Holman" | "Holmes" | "Holt" | "Honeycutt" | "Hood" | "Hooker" 
	| "Hooks" | "Hooper" | "Hoover" | "Hope" | "Hopkins" | "Hopper" | "Horn" | "Horne" | "Horner" | "Horton" | "Hoskins" | "Hough" 
	| "House" | "Houser" | "Houston" | "Howard" | "Howe" | "Howell" | "Hoyt" | "Hubbard" | "Huber" | "Huddleston" | "Hudson" | "Huerta" 
	| "Huff" | "Huffman" | "Huggins" | "Hughes" | "Hull" | "Humphrey" | "Hunt" | "Hunter" | "Hurd" | "Hurley" | "Hurst" | "Hurt" 
	| "Hutchins" | "Hutchinson" | "Hutchison" | "Hutton" | "Huynh" | "Hyatt" | "Hyde" | "Ibarra" | "Ingram" | "Inman" | "Irvin" 
	| "Irving" | "Irwin" | "Isaac" | "Ivey" | "Jack" | "Jackson" | "Jacob" | "Jacobs" | "Jacobsen" | "Jacobson" | "James" | "Jamison" 
	| "Jaramillo" | "Jarrett" | "Jarvis" | "Jean" | "Jeffers" | "Jefferson" | "Jeffries" | "Jenkins" | "Jennings" | "Jensen" 
	| "Jernigan" | "Jewell" | "Jimenez" | "John" | "Johns" | "Johnson" | "Johnston" | "Joiner" | "Jolly" | "Jones" | "Jordan" 
	| "Jorgensen" | "Joseph" | "Joyce" | "Joyner" | "Juarez" | "Judd" | "Justice" | "Kaiser" | "Kane" | "Kaplan" | "Katz" | "Kauffman" 
	| "Kaufman" | "Kay" | "Kearney" | "Keen" | "Keenan" | "Keene" | "Keith" | "Keller" | "Kelley" | "Kelly" | "Kemp" | "Kendall" 
	| "Kendrick" | "Kennedy" | "Kenney" | "Kenny" | "Kent" | "Kern" | "Kerns" | "Kerr" | "Kessler" | "Key" | "Keyes" | "Keys" | "Khan" 
	| "Kidd" | "Kilgore" | "Kim" | "Kimball" | "Kimble" | "Kincaid" | "King" | "Kinney" | "Kirby" | "Kirk" | "Kirkland" | "Kirkpatrick" 
	| "Kiser" | "Klein" | "Kline" | "Knapp" | "Knight" | "Knowles" | "Knox" | "Knutson" | "Koch" | "Koehler" | "Koenig" | "Kraft" 
	| "Kramer" | "Krause" | "Krueger" | "Kruse" | "Kuhn" | "Kurtz" | "Kyle" | "Lacey" | "Lackey" | "Lacy" | "Ladd" | "Ladner" | "Laird" 
	| "Lake" | "Lam" | "Lamb" | "Lambert" | "Lancaster" | "Land" | "Landers" | "Landis" | "Landry" | "Lane" | "Lang" | "Lange" 
	| "Langford" | "Langley" | "Langston" | "Lanier" | "Lara" | "Larkin" | "Larsen" | "Larson" | "Lassiter" | "Latham" | "Law" 
	| "Lawrence" | "Lawson" | "Lay" | "Le" | "Leach" | "Leal" | "Leary" | "Leblanc" | "Ledbetter" | "Ledford" | "Lee" | "Lehman" 
	| "Leon" | "Leonard" | "Leslie" | "Lester" | "Levine" | "Levy" | "Lewis" | "Light" | "Lilly" | "Lim" | "Lin" | "Lindsay" | "Lindsey" 
	| "Link" | "Little" | "Livingston" | "Lloyd" | "Locke" | "Lockett" | "Lockhart" | "Lockwood" | "Logan" | "London" | "Long" 
	| "Longoria" | "Loomis" | "Looney" | "Lopez" | "Lord" | "Lott" | "Louis" | "Love" | "Lovell" | "Lovett" | "Lowe" | "Lowery" 
	| "Lowry" | "Lozano" | "Lucas" | "Lucero" | "Ludwig" | "Lugo" | "Lujan" | "Luna" | "Lund" | "Lundy" | "Lunsford" | "Lusk" | "Lutz" 
	| "Lyles" | "Lynch" | "Lynn" | "Lyon" | "Lyons" | "Macdonald" | "Macias" | "Mack" | "Mackey" | "Madden" | "Maddox" | "Madison" 
	| "Madrid" | "Magee" | "Maher" | "Mahoney" | "Major" | "Maldonado" | "Malone" | "Maloney" | "Manley" | "Mann" | "Manning" 
	| "Mansfield" | "Manuel" | "Marcum" | "Marcus" | "Marin" | "Marino" | "Marion" | "Marks" | "Marquez" | "Marrero" | "Marsh" 
	| "Marshall" | "Martin" | "Martinez" | "Mason" | "Massey" | "Masters" | "Mata" | "Mathews" | "Mathis" | "Matos" | "Matthews" 
	| "Maurer" | "Maxwell" | "May" | "Mayberry" | "Mayer" | "Mayes" | "Mayfield" | "Maynard" | "Mayo" | "Mays" | "Mcallister" 
	| "Mcbride" | "Mccabe" | "Mccain" | "Mccall" | "Mccann" | "Mccarthy" | "Mccarty" | "Mccauley" | "Mcclain" | "Mcclellan" 
	| "Mcclendon" | "Mccloud" | "Mcclure" | "Mccollum" | "Mcconnell" | "Mccord" | "Mccormick" | "Mccoy" | "Mccracken" | "Mccray" 
	| "Mccullough" | "Mcdaniel" | "Mcdermott" | "Mcdonald" | "Mcdonough" | "Mcdowell" | "Mcelroy" | "Mcfadden" | "Mcfarland" | "Mcgee" 
	| "Mcghee" | "Mcgill" | "Mcginnis" | "Mcgowan" | "Mcgrath" | "Mcgraw" | "Mcguire" | "Mcintosh" | "Mcintyre" | "Mckay" | "Mckee" 
	| "Mckenna" | "Mckenzie" | "Mckinley" | "Mckinney" | "Mckinnon" | "Mcknight" | "Mclain" | "Mclaughlin" | "Mclean" | "Mcleod" 
	| "Mcmahon" | "Mcmanus" | "Mcmillan" | "Mcmullen" | "Mcnair" | "Mcnally" | "Mcnamara" | "Mcneal" | "Mcneil" | "Mcneill" 
	| "Mcpherson" | "Mcqueen" | "Mcrae" | "Mcwilliams" | "Mead" | "Meade" | "Meadows" | "Means" | "Medeiros" | "Medina" | "Medrano" 
	| "Meeks" | "Meier" | "Mejia" | "Melendez" | "Melton" | "Melvin" | "Mendez" | "Mendoza" | "Mercado" | "Mercer" | "Meredith" 
	| "Merrill" | "Merritt" | "Messer" | "Metcalf" | "Metz" | "Meyer" | "Meyers" | "Meza" | "Michael" | "Michaud" | "Michel" 
	| "Middleton" | "Miles" | "Miller" | "Milligan" | "Mills" | "Milton" | "Mims" | "Miner" | "Minor" | "Miranda" | "Mitchell" 
	| "Mobley" | "Mock" | "Mohr" | "Molina" | "Monroe" | "Montano" | "Montes" | "Montgomery" | "Montoya" | "Moody" | "Moon" | "Mooney" 
	| "Moore" | "Mora" | "Morales" | "Moran" | "Moreland" | "Moreno" | "Morgan" | "Morin" | "Morris" | "Morrison" | "Morrow" | "Morse" 
	| "Morton" | "Moseley" | "Moser" | "Moses" | "Mosley" | "Moss" | "Moyer" | "Mueller" | "Mullen" | "Muller" | "Mullins" | "Muniz" 
	| "Munoz" | "Munson" | "Murdock" | "Murillo" | "Murphy" | "Murray" | "Myers" | "Myles" | "Myrick" | "Nadeau" | "Nance" | "Napier" 
	| "Naquin" | "Nash" | "Nava" | "Navarro" | "Naylor" | "Neal" | "Neely" | "Neff" | "Negron" | "Nelson" | "Newell" | "Newman" 
	| "Newsome" | "Newton" | "Nguyen" | "Nicholas" | "Nichols" | "Nicholson" | "Nickerson" | "Nielsen" | "Nieves" | "Nix" | "Nixon" 
	| "Noble" | "Noel" | "Nolan" | "Norman" | "Norris" | "North" | "Norton" | "Norwood" | "Novak" | "Numbers" | "Nunez" | "Oakes" 
	| "Oakley" | "Obrien" | "Ochoa" | "Oconnell" | "Oconnor" | "Odell" | "Odom" | "Odonnell" | "Ogden" | "Ohara" | "Oleary" | "Oliver" 
	| "Olsen" | "Olson" | "Oneal" | "Oneil" | "Oneill" | "Orozco" | "Orr" | "Ortega" | "Ortiz" | "Osborn" | "Osborne" | "Otero" | "Ott" 
	| "Otto" | "Ouellette" | "Overton" | "Owen" | "Owens" | "Pace" | "Pacheco" | "Pack" | "Padgett" | "Padilla" | "Pagan" | "Page" 
	| "Paige" | "Painter" | "Palacios" | "Palmer" | "Parham" | "Park" | "Parker" | "Parks" | "Parr" | "Parra" | "Parrish" | "Parson" 
	| "Parsons" | "Pate" | "Patel" | "Patrick" | "Patterson" | "Patton" | "Paul" | "Paulson" | "Payne" | "Payton" | "Peacock" | "Pearce" 
	| "Pearson" | "Peck" | "Pelletier" | "Pena" | "Pendleton" | "Penn" | "Pennington" | "Peoples" | "Perdue" | "Pereira" | "Perez" 
	| "Perkins" | "Perry" | "Person" | "Peters" | "Petersen" | "Peterson" | "Pettit" | "Petty" | "Pham" | "Phelps" | "Phillips" 
	| "Phipps" | "Pickens" | "Pickett" | "Pierce" | "Pierre" | "Pierson" | "Pike" | "Pina" | "Pineda" | "Piper" | "Pittman" | "Pitts" 
	| "Platt" | "Plummer" | "Poe" | "Polk" | "Pollard" | "Pollock" | "Ponce" | "Pool" | "Poole" | "Pope" | "Porter" | "Posey" | "Post" 
	| "Potter" | "Potts" | "Powell" | "Powers" | "Prater" | "Prather" | "Pratt" | "Prescott" | "Presley" | "Preston" | "Price" 
	| "Prince" | "Pritchard" | "Pritchett" | "Proctor" | "Pruitt" | "Pryor" | "Puckett" | "Pugh" | "Purcell" | "Purvis" | "Putnam" 
	| "Queen" | "Quick" | "Quinn" | "Quinones" | "Quintana" | "Quintero" | "Ragland" | "Raines" | "Rainey" | "Ramey" | "Ramirez" 
	| "Ramos" | "Ramsey" | "Randall" | "Randle" | "Randolph" | "Rangel" | "Rankin" | "Ransom" | "Rasmussen" | "Ratliff" | "Ray" 
	| "Raymond" | "Read" | "Reagan" | "Reaves" | "Redmond" | "Reece" | "Reed" | "Reeder" | "Reese" | "Reeves" | "Reid" | "Reilly" 
	| "Reyes" | "Reyna" | "Reynolds" | "Rhoades" | "Rhodes" | "Rice" | "Rich" | "Richard" | "Richards" | "Richardson" | "Richey" 
	| "Richmond" | "Richter" | "Ricks" | "Riddle" | "Riggs" | "Riley" | "Rios" | "Ritchie" | "Ritter" | "Rivas" | "Rivera" | "Rivers" 
	| "Roach" | "Roark" | "Robbins" | "Roberson" | "Roberts" | "Robertson" | "Robinson" | "Robison" | "Robles" | "Rocha" | "Rock" 
	| "Rodgers" | "Rodrigues" | "Rodriguez" | "Rodriquez" | "Roe" | "Rogers" | "Rojas" | "Roland" | "Rollins" | "Roman" | "Romano" 
	| "Romero" | "Romo" | "Root" | "Roper" | "Rosa" | "Rosado" | "Rosales" | "Rosario" | "Rosas" | "Rose" | "Rosen" | "Rosenberg" 
	| "Ross" | "Rossi" | "Roth" | "Rouse" | "Rowe" | "Rowell" | "Rowland" | "Roy" | "Rubin" | "Rubio" | "Rucker" | "Rudd" | "Rudolph" 
	| "Ruffin" | "Ruiz" | "Rush" | "Rushing" | "Russell" | "Russo" | "Rutherford" | "Rutledge" | "Ryan" | "Sadler" | "Saenz" | "Salas" 
	| "Salazar" | "Saldana" | "Salgado" | "Salinas" | "Salter" | "Sampson" | "Sams" | "Samuel" | "Samuels" | "Sanchez" | "Sanders" 
	| "Sanderson" | "Sandoval" | "Sands" | "Sanford" | "Santana" | "Santiago" | "Santos" | "Sapp" | "Sargent" | "Saunders" | "Savage" 
	| "Sawyer" | "Schaefer" | "Schafer" | "Schaffer" | "Schmidt" | "Schmitt" | "Schmitz" | "Schneider" | "Schroeder" | "Schultz" 
	| "Schulz" | "Schwartz" | "Scott" | "Scruggs" | "Seals" | "Sears" | "Seay" | "Segura" | "Self" | "Sellers" | "Serrano" | "Sewell" 
	| "Sexton" | "Seymour" | "Shafer" | "Shaffer" | "Shannon" | "Shapiro" | "Sharp" | "Sharpe" | "Shaver" | "Shaw" | "Shea" | "Shearer" 
	| "Sheehan" | "Sheets" | "Sheffield" | "Sheldon" | "Shelton" | "Shepard" | "Shepherd" | "Sheppard" | "Sheridan" | "Sherman" 
	| "Sherrill" | "Sherwood" | "Shields" | "Shipley" | "Shipman" | "Shirley" | "Shoemaker" | "Shook" | "Short" | "Shultz" | "Siegel" 
	| "Sierra" | "Silva" | "Silver" | "Simmons" | "Simms" | "Simon" | "Simons" | "Simpson" | "Sims" | "Sinclair" | "Singer" | "Singh" 
	| "Singleton" | "Sizemore" | "Skaggs" | "Skinner" | "Slater" | "Slaughter" | "Sloan" | "Small" | "Smallwood" | "Smart" | "Smiley" 
	| "Smith" | "Sneed" | "Snell" | "Snider" | "Snow" | "Snyder" | "Solis" | "Solomon" | "Sorensen" | "Sosa" | "Soto" | "Souza" 
	| "Spangler" | "Sparks" | "Spaulding" | "Spears" | "Spence" | "Spencer" | "Spicer" | "Spivey" | "Sprague" | "Springer" | "Stacy" 
	| "Stafford" | "Stahl" | "Staley" | "Stallings" | "Stanford" | "Stanley" | "Stanton" | "Staples" | "Stapleton" | "Stark" | "Starks" 
	| "Starnes" | "Starr" | "Staton" | "Steele" | "Stein" | "Steiner" | "Stephens" | "Stephenson" | "Sterling" | "Stern" | "Stevens" 
	| "Stevenson" | "Steward" | "Stewart" | "Stiles" | "Stinson" | "Stokes" | "Stone" | "Story" | "Stout" | "Stovall" | "Stover" 
	| "Stratton" | "Street" | "Strickland" | "Stringer" | "Strong" | "Stroud" | "Stuart" | "Stubbs" | "Suarez" | "Suggs" | "Sullivan" 
	| "Summers" | "Sumner" | "Sutherland" | "Sutton" | "Swain" | "Swan" | "Swanson" | "Swartz" | "Sweeney" | "Sweet" | "Swenson" 
	| "Swift" | "Sykes" | "Sylvester" | "Tabor" | "Tackett" | "Talbot" | "Talley" | "Tanner" | "Tapia" | "Tate" | "Tatum" | "Taylor" 
	| "Teague" | "Temple" | "Terrell" | "Terry" | "Thacker" | "Thayer" | "Thomas" | "Thomason" | "Thompson" | "Thomson" | "Thorne" 
	| "Thornton" | "Thorpe" | "Thurman" | "Tidwell" | "Tilley" | "Tillman" | "Timmons" | "Tipton" | "Tobin" | "Todd" | "Tolbert" 
	| "Tomlinson" | "Tompkins" | "Toney" | "Torres" | "Tovar" | "Townsend" | "Tracy" | "Tran" | "Travis" | "Trejo" | "Trent" | "Trevino" 
	| "Triplett" | "Tripp" | "Trotter" | "Trujillo" | "Tucker" | "Turner" | "Tuttle" | "Tyler" | "Tyson" | "Underwood" | "Valdez" 
	| "Valencia" | "Valentin" | "Valentine" | "Valenzuela" | "Valle" | "Vance" | "Vang" | "Vann" | "Vargas" | "Varner" | "Vasquez" 
	| "Vaughan" | "Vaughn" | "Vazquez" | "Vega" | "Vela" | "Velasquez" | "Velazquez" | "Velez" | "Ventura" | "Vera" | "Vernon" | "Vick" 
	| "Vickers" | "Vigil" | "Villa" | "Villalobos" | "Villanueva" | "Villarreal" | "Villegas" | "Vincent" | "Vinson" | "Vogel" | "Vogt" 
	| "Voss" | "Waddell" | "Wade" | "Wagner" | "Walden" | "Waldron" | "Walker" | "Wall" | "Wallace" | "Waller" | "Walls" | "Walsh" 
	| "Walter" | "Walters" | "Walton" | "Wang" | "Ward" | "Ware" | "Warner" | "Warren" | "Washburn" | "Washington" | "Waters" 
	| "Watkins" | "Watson" | "Watts" | "Weaver" | "Webb" | "Webber" | "Weber" | "Webster" | "Weeks" | "Weir" | "Weiss" | "Welch" 
	| "Wells" | "Welsh" | "Werner" | "Wesley" | "West" | "Westbrook" | "Weston" | "Whalen" | "Whaley" | "Wheeler" | "Whitaker" | "White" 
	| "Whitehead" | "Whitfield" | "Whitley" | "Whitlock" | "Whitman" | "Whitney" | "Whitt" | "Whittaker" | "Whitten" | "Wiggins" 
	| "Wilcox" | "Wilder" | "Wiley" | "Wilkerson" | "Wilkes" | "Wilkins" | "Wilkinson" | "Willard" | "William" | "Williams" 
	| "Williamson" | "Willis" | "Wills" | "Wilson" | "Winkler" | "Winn" | "Winslow" | "Winston" | "Winter" | "Winters" | "Wise" 
	| "Wiseman" | "Witherspoon" | "Witt" | "Wolf" | "Wolfe" | "Wolff" | "Womack" | "Wong" | "Wood" | "Woodall" | "Woodard" | "Woodruff" 
	| "Woods" | "Woodson" | "Woodward" | "Woody" | "Wooten" | "Workman" | "Worley" | "Wray" | "Wright" | "Wu" | "Wyatt" | "Wynn" 
	| "Xiong" | "Yang" | "Yarbrough" | "Yates" | "Yazzie" | "Ybarra" | "Yeager" | "Yoder" | "York" | "Young" | "Youngblood" | "Yu" 
	| "Zamora" | "Zapata" | "Zavala" | "Ziegler" | "Zimmerman" | "Zuniga"
;

%resource male-name:
	male-first-name " " last-name | male-first-name " " male-first-name " " last-name
	| male-first-name " " last-name "-" last-name | male-first-name " " male-first-name " " last-name "-" last-name
;

%resource female-name:
	female-first-name " " last-name | female-first-name " " female-first-name " " last-name
	| female-first-name " " last-name "-" last-name | female-first-name " " female-first-name " " last-name "-" last-name
;

%resource person-name:
	male-name | female-name
;